spring.application.name=mud_cafe

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mud_cafe_db
spring.datasource.username=postgres
spring.datasource.password=Varun@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=mud_cafe_super_secret_jwt_key_2024_varun_restaurant_billing_app
jwt.expiration=86400000

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Firebase - configure later
# firebase.credentials.path=classpath:firebase-service-account.json